/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CreateInviteResult = { 'ok' : string } |
  { 'error' : string };
export type ExternalBlob = Uint8Array;
export interface InviteCode {
  'created' : Time,
  'code' : string,
  'used' : boolean,
}
export interface InvitePayload {
  'galleryImages' : Array<ExternalBlob>,
  'weddingDate' : string,
  'groomPhoto' : ExternalBlob,
  'themeVariant' : string,
  'templateId' : string,
  'customTextFields' : Array<[string, string]>,
  'sectionsConfig' : Array<[string, SectionConfig]>,
  'coverPhoto' : ExternalBlob,
  'events' : Array<ScheduleItem>,
  'coupleNames' : string,
  'backgroundMusic' : string,
  'bridePhoto' : ExternalBlob,
}
export interface InviteRecord {
  'id' : string,
  'galleryImages' : Array<ExternalBlob>,
  'weddingDate' : string,
  'groomPhoto' : ExternalBlob,
  'themeVariant' : string,
  'templateId' : string,
  'customTextFields' : Array<[string, string]>,
  'createdAt' : bigint,
  'sectionsConfig' : Array<[string, SectionConfig]>,
  'isSample' : boolean,
  'coverPhoto' : ExternalBlob,
  'events' : Array<ScheduleItem>,
  'creatorPrincipal' : Principal,
  'coupleNames' : string,
  'backgroundMusic' : string,
  'rsvpResponses' : Array<RSVPRecord>,
  'bridePhoto' : ExternalBlob,
}
export interface RSVP {
  'name' : string,
  'inviteCode' : string,
  'timestamp' : Time,
  'attending' : boolean,
}
export interface RSVPRecord {
  'name' : string,
  'attendance' : boolean,
  'message' : string,
  'guests' : bigint,
}
export interface ScheduleItem {
  'venue' : string,
  'name' : string,
  'time' : string,
  'details' : string,
}
export interface SectionConfig {
  'isActive' : boolean,
  'customTitle' : string,
  'customText' : string,
}
export type Time = bigint;
export type UpdateInviteResult = { 'ok' : null } |
  { 'error' : string };
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createInvite' : ActorMethod<[string, InvitePayload], CreateInviteResult>,
  'generateInviteCode' : ActorMethod<[], string>,
  'getAllRSVPs' : ActorMethod<[], Array<RSVP>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInvite' : ActorMethod<[string], [] | [InviteRecord]>,
  'getInviteCodes' : ActorMethod<[], Array<InviteCode>>,
  'getInviteCreator' : ActorMethod<[string], [] | [Principal]>,
  'getMyInvites' : ActorMethod<[], Array<InviteRecord>>,
  'getRSVPResponses' : ActorMethod<[string], Array<RSVPRecord>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitInviteRSVP' : ActorMethod<[string, RSVPRecord], undefined>,
  'submitRSVP' : ActorMethod<[string, boolean, string], undefined>,
  'updateInvite' : ActorMethod<[string, InvitePayload], UpdateInviteResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];