/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ScheduleItem {
    venue: string;
    name: string;
    time: string;
    details: string;
}
export interface RSVPRecord {
    name: string;
    attendance: boolean;
    message: string;
    guests: bigint;
}
export interface InviteRecord {
    id: string;
    galleryImages: Array<ExternalBlob>;
    weddingDate: string;
    groomPhoto: ExternalBlob;
    themeVariant: string;
    templateId: string;
    customTextFields: Array<[string, string]>;
    createdAt: bigint;
    sectionsConfig: Array<[string, SectionConfig]>;
    isSample: boolean;
    coverPhoto: ExternalBlob;
    events: Array<ScheduleItem>;
    coupleNames: string;
    backgroundMusic: string;
    rsvpResponses: Array<RSVPRecord>;
    bridePhoto: ExternalBlob;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface SectionConfig {
    isActive: boolean;
    customTitle: string;
    customText: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface InvitePayload {
    galleryImages: Array<ExternalBlob>;
    weddingDate: string;
    groomPhoto: ExternalBlob;
    themeVariant: string;
    templateId: string;
    customTextFields: Array<[string, string]>;
    sectionsConfig: Array<[string, SectionConfig]>;
    coverPhoto: ExternalBlob;
    events: Array<ScheduleItem>;
    coupleNames: string;
    backgroundMusic: string;
    bridePhoto: ExternalBlob;
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    createInvite(id: string, payload: InvitePayload): Promise<string>;
    getInvite(id: string): Promise<InviteRecord | null>;
    listSampleInvites(): Promise<Array<InviteRecord>>;
    submitRSVP(id: string, rsvp: RSVPRecord): Promise<void>;
    updateInvite(id: string, payload: InvitePayload): Promise<void>;
}
import type { ExternalBlob as _ExternalBlob, InvitePayload as _InvitePayload, InviteRecord as _InviteRecord, RSVPRecord as _RSVPRecord, ScheduleItem as _ScheduleItem, SectionConfig as _SectionConfig, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async createInvite(arg0: string, arg1: InvitePayload): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createInvite(arg0, await to_candid_InvitePayload_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInvite(arg0, await to_candid_InvitePayload_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getInvite(arg0: string): Promise<InviteRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvite(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvite(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async listSampleInvites(): Promise<Array<InviteRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSampleInvites();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSampleInvites();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitRSVP(arg0: string, arg1: RSVPRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitRSVP(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitRSVP(arg0, arg1);
            return result;
        }
    }
    async updateInvite(arg0: string, arg1: InvitePayload): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInvite(arg0, await to_candid_InvitePayload_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInvite(arg0, await to_candid_InvitePayload_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
async function from_candid_ExternalBlob_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_InviteRecord_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InviteRecord): Promise<InviteRecord> {
    return await from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_InviteRecord]): Promise<InviteRecord | null> {
    return value.length === 0 ? null : await from_candid_InviteRecord_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    galleryImages: Array<_ExternalBlob>;
    weddingDate: string;
    groomPhoto: _ExternalBlob;
    themeVariant: string;
    templateId: string;
    customTextFields: Array<[string, string]>;
    createdAt: bigint;
    sectionsConfig: Array<[string, _SectionConfig]>;
    isSample: boolean;
    coverPhoto: _ExternalBlob;
    events: Array<_ScheduleItem>;
    coupleNames: string;
    backgroundMusic: string;
    rsvpResponses: Array<_RSVPRecord>;
    bridePhoto: _ExternalBlob;
}): Promise<{
    id: string;
    galleryImages: Array<ExternalBlob>;
    weddingDate: string;
    groomPhoto: ExternalBlob;
    themeVariant: string;
    templateId: string;
    customTextFields: Array<[string, string]>;
    createdAt: bigint;
    sectionsConfig: Array<[string, SectionConfig]>;
    isSample: boolean;
    coverPhoto: ExternalBlob;
    events: Array<ScheduleItem>;
    coupleNames: string;
    backgroundMusic: string;
    rsvpResponses: Array<RSVPRecord>;
    bridePhoto: ExternalBlob;
}> {
    return {
        id: value.id,
        galleryImages: await from_candid_vec_n15(_uploadFile, _downloadFile, value.galleryImages),
        weddingDate: value.weddingDate,
        groomPhoto: await from_candid_ExternalBlob_n16(_uploadFile, _downloadFile, value.groomPhoto),
        themeVariant: value.themeVariant,
        templateId: value.templateId,
        customTextFields: value.customTextFields,
        createdAt: value.createdAt,
        sectionsConfig: value.sectionsConfig,
        isSample: value.isSample,
        coverPhoto: await from_candid_ExternalBlob_n16(_uploadFile, _downloadFile, value.coverPhoto),
        events: value.events,
        coupleNames: value.coupleNames,
        backgroundMusic: value.backgroundMusic,
        rsvpResponses: value.rsvpResponses,
        bridePhoto: await from_candid_ExternalBlob_n16(_uploadFile, _downloadFile, value.bridePhoto)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
async function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n16(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InviteRecord>): Promise<Array<InviteRecord>> {
    return await Promise.all(value.map(async (x)=>await from_candid_InviteRecord_n13(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_InvitePayload_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InvitePayload): Promise<_InvitePayload> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    galleryImages: Array<ExternalBlob>;
    weddingDate: string;
    groomPhoto: ExternalBlob;
    themeVariant: string;
    templateId: string;
    customTextFields: Array<[string, string]>;
    sectionsConfig: Array<[string, SectionConfig]>;
    coverPhoto: ExternalBlob;
    events: Array<ScheduleItem>;
    coupleNames: string;
    backgroundMusic: string;
    bridePhoto: ExternalBlob;
}): Promise<{
    galleryImages: Array<_ExternalBlob>;
    weddingDate: string;
    groomPhoto: _ExternalBlob;
    themeVariant: string;
    templateId: string;
    customTextFields: Array<[string, string]>;
    sectionsConfig: Array<[string, _SectionConfig]>;
    coverPhoto: _ExternalBlob;
    events: Array<_ScheduleItem>;
    coupleNames: string;
    backgroundMusic: string;
    bridePhoto: _ExternalBlob;
}> {
    return {
        galleryImages: await to_candid_vec_n10(_uploadFile, _downloadFile, value.galleryImages),
        weddingDate: value.weddingDate,
        groomPhoto: await to_candid_ExternalBlob_n11(_uploadFile, _downloadFile, value.groomPhoto),
        themeVariant: value.themeVariant,
        templateId: value.templateId,
        customTextFields: value.customTextFields,
        sectionsConfig: value.sectionsConfig,
        coverPhoto: await to_candid_ExternalBlob_n11(_uploadFile, _downloadFile, value.coverPhoto),
        events: value.events,
        coupleNames: value.coupleNames,
        backgroundMusic: value.backgroundMusic,
        bridePhoto: await to_candid_ExternalBlob_n11(_uploadFile, _downloadFile, value.bridePhoto)
    };
}
async function to_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n11(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
