/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const SectionConfig = IDL.Record({
  'isActive' : IDL.Bool,
  'customTitle' : IDL.Text,
  'customText' : IDL.Text,
});
export const ScheduleItem = IDL.Record({
  'venue' : IDL.Text,
  'name' : IDL.Text,
  'time' : IDL.Text,
  'details' : IDL.Text,
});
export const InvitePayload = IDL.Record({
  'galleryImages' : IDL.Vec(ExternalBlob),
  'weddingDate' : IDL.Text,
  'groomPhoto' : ExternalBlob,
  'themeVariant' : IDL.Text,
  'templateId' : IDL.Text,
  'customTextFields' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'sectionsConfig' : IDL.Vec(IDL.Tuple(IDL.Text, SectionConfig)),
  'coverPhoto' : ExternalBlob,
  'events' : IDL.Vec(ScheduleItem),
  'coupleNames' : IDL.Text,
  'backgroundMusic' : IDL.Text,
  'bridePhoto' : ExternalBlob,
});
export const RSVPRecord = IDL.Record({
  'name' : IDL.Text,
  'attendance' : IDL.Bool,
  'message' : IDL.Text,
  'guests' : IDL.Nat,
});
export const InviteRecord = IDL.Record({
  'id' : IDL.Text,
  'galleryImages' : IDL.Vec(ExternalBlob),
  'weddingDate' : IDL.Text,
  'groomPhoto' : ExternalBlob,
  'themeVariant' : IDL.Text,
  'templateId' : IDL.Text,
  'customTextFields' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'createdAt' : IDL.Int,
  'sectionsConfig' : IDL.Vec(IDL.Tuple(IDL.Text, SectionConfig)),
  'isSample' : IDL.Bool,
  'coverPhoto' : ExternalBlob,
  'events' : IDL.Vec(ScheduleItem),
  'coupleNames' : IDL.Text,
  'backgroundMusic' : IDL.Text,
  'rsvpResponses' : IDL.Vec(RSVPRecord),
  'bridePhoto' : ExternalBlob,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'createInvite' : IDL.Func([IDL.Text, InvitePayload], [IDL.Text], []),
  'getInvite' : IDL.Func([IDL.Text], [IDL.Opt(InviteRecord)], ['query']),
  'listSampleInvites' : IDL.Func([], [IDL.Vec(InviteRecord)], ['query']),
  'submitRSVP' : IDL.Func([IDL.Text, RSVPRecord], [], []),
  'updateInvite' : IDL.Func([IDL.Text, InvitePayload], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const SectionConfig = IDL.Record({
    'isActive' : IDL.Bool,
    'customTitle' : IDL.Text,
    'customText' : IDL.Text,
  });
  const ScheduleItem = IDL.Record({
    'venue' : IDL.Text,
    'name' : IDL.Text,
    'time' : IDL.Text,
    'details' : IDL.Text,
  });
  const InvitePayload = IDL.Record({
    'galleryImages' : IDL.Vec(ExternalBlob),
    'weddingDate' : IDL.Text,
    'groomPhoto' : ExternalBlob,
    'themeVariant' : IDL.Text,
    'templateId' : IDL.Text,
    'customTextFields' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'sectionsConfig' : IDL.Vec(IDL.Tuple(IDL.Text, SectionConfig)),
    'coverPhoto' : ExternalBlob,
    'events' : IDL.Vec(ScheduleItem),
    'coupleNames' : IDL.Text,
    'backgroundMusic' : IDL.Text,
    'bridePhoto' : ExternalBlob,
  });
  const RSVPRecord = IDL.Record({
    'name' : IDL.Text,
    'attendance' : IDL.Bool,
    'message' : IDL.Text,
    'guests' : IDL.Nat,
  });
  const InviteRecord = IDL.Record({
    'id' : IDL.Text,
    'galleryImages' : IDL.Vec(ExternalBlob),
    'weddingDate' : IDL.Text,
    'groomPhoto' : ExternalBlob,
    'themeVariant' : IDL.Text,
    'templateId' : IDL.Text,
    'customTextFields' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'createdAt' : IDL.Int,
    'sectionsConfig' : IDL.Vec(IDL.Tuple(IDL.Text, SectionConfig)),
    'isSample' : IDL.Bool,
    'coverPhoto' : ExternalBlob,
    'events' : IDL.Vec(ScheduleItem),
    'coupleNames' : IDL.Text,
    'backgroundMusic' : IDL.Text,
    'rsvpResponses' : IDL.Vec(RSVPRecord),
    'bridePhoto' : ExternalBlob,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'createInvite' : IDL.Func([IDL.Text, InvitePayload], [IDL.Text], []),
    'getInvite' : IDL.Func([IDL.Text], [IDL.Opt(InviteRecord)], ['query']),
    'listSampleInvites' : IDL.Func([], [IDL.Vec(InviteRecord)], ['query']),
    'submitRSVP' : IDL.Func([IDL.Text, RSVPRecord], [], []),
    'updateInvite' : IDL.Func([IDL.Text, InvitePayload], [], []),
  });
};

export const init = ({ IDL }) => { return []; };