/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface InvitePayload {
  'galleryImages' : Array<ExternalBlob>,
  'weddingDate' : string,
  'groomPhoto' : ExternalBlob,
  'themeVariant' : string,
  'templateId' : string,
  'customTextFields' : Array<[string, string]>,
  'sectionsConfig' : Array<[string, SectionConfig]>,
  'coverPhoto' : ExternalBlob,
  'events' : Array<ScheduleItem>,
  'coupleNames' : string,
  'backgroundMusic' : string,
  'bridePhoto' : ExternalBlob,
}
export interface InviteRecord {
  'id' : string,
  'galleryImages' : Array<ExternalBlob>,
  'weddingDate' : string,
  'groomPhoto' : ExternalBlob,
  'themeVariant' : string,
  'templateId' : string,
  'customTextFields' : Array<[string, string]>,
  'createdAt' : bigint,
  'sectionsConfig' : Array<[string, SectionConfig]>,
  'isSample' : boolean,
  'coverPhoto' : ExternalBlob,
  'events' : Array<ScheduleItem>,
  'coupleNames' : string,
  'backgroundMusic' : string,
  'rsvpResponses' : Array<RSVPRecord>,
  'bridePhoto' : ExternalBlob,
}
export interface RSVPRecord {
  'name' : string,
  'attendance' : boolean,
  'message' : string,
  'guests' : bigint,
}
export interface ScheduleItem {
  'venue' : string,
  'name' : string,
  'time' : string,
  'details' : string,
}
export interface SectionConfig {
  'isActive' : boolean,
  'customTitle' : string,
  'customText' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'createInvite' : ActorMethod<[string, InvitePayload], string>,
  'getInvite' : ActorMethod<[string], [] | [InviteRecord]>,
  'listSampleInvites' : ActorMethod<[], Array<InviteRecord>>,
  'submitRSVP' : ActorMethod<[string, RSVPRecord], undefined>,
  'updateInvite' : ActorMethod<[string, InvitePayload], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];